[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coniii"
description = "Convenient Interface to Inverse Ising (ConIII)"
readme = "README.md"
requires-python = ">=3.8.3"
license = {text = "MIT"}
authors = [
    {name = "Edward D. Lee", email = "edlee@csh.ac.at"},
    {name = "Bryan C Daniels", email = "bryan.daniels.1@asu.edu"},
]
keywords = ["inverse", "Ising", "maxent", "maximum entropy", "inference"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "multiprocess>=0.70.7,<1",
    "scipy",
    "matplotlib",
    "numpy>=1.16.2,<2",
    "numba>=0.45.1,<1",
    "mpmath>=1.1.0",
    "dill",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Homepage = "https://github.com/eltrompetero/coniii"
"Bug Tracker" = "https://github.com/eltrompetero/coniii/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["coniii*"]

[tool.setuptools.dynamic]
version = {attr = "coniii.version.version"}
